# ---------------------------------------
# Global
# ---------------------------------------

stages:
  - "Package"
  - "Deploy"

# ----------------------------------------
# Prescript
# ----------------------------------------

# ----------------------------------------
# Build
# ----------------------------------------

# ----------------------------------------
# Package
# ----------------------------------------

package-as-zip:
  stage: "Package"
  image: alpine:latest
  script:
    - apk add -U zip
    - sh build/package.sh
  artifacts:
    expire_in: 4 weeks
    paths:
      - "!artifacts/*.zip"

# ----------------------------------------
# Deploy
# ----------------------------------------

deploy-to-git:
  stage: "Deploy"
  image: alpine:latest
  script:
    - sh build/deploy.sh
  only:
    - master